apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-go
spec:
  steps:
    - name: test
      image: golang:1.22
      workingDir: /workspace/source
      script: |
        go test ./...
  workspaces:
    - name: source
