apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-project-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: "main"
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build
      taskRef:
        name: build-go
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - clone
    - name: test
      taskRef:
        name: test-go
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - build
